### ISSUE TITLE
 sympy 1.2 changed how indexing works upon immutable dense matrix.

### ISSUE THREAD

**Issue by extraymond** [pydy/pydy#395]
Greetings, in sympy 1.1.1, when indexing on immutable dense matrix, the results will be a list, however in 1.2 the results is a set.

The behavior difference show regression when initiating a pydy.system.System instance.

The error log:

```python

sys = System(kane)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/git/xr_practice_back/xr_practice_back/basic.py in <module>()                                                                                                                                                       
     40 eom = fr + frstar            
     41                                                                                                      
---> 42 sys = System(kane)                                                    
     43 #                                                    
     44 # sys.initial_conditions = {i: j for i, j in zip(pos+speeds, [0, 0, 4, 3])}
                                                                                     
~/.pyenv/versions/pypy3.5-6.0.0/envs/xr_practice_back/site-packages/pydy/system.py in __init__(self, eom_method, constants, specifieds, ode_solver, initial_conditions, times)
    103
    104         # TODO : What if user adds symbols after constructing a System?
--> 105         self._constants_symbols = self._Kane_constant_symbols()
    106         self._specifieds_symbols = self._Kane_undefined_dynamicsymbols()
    107             

~/.pyenv/versions/pypy3.5-6.0.0/envs/xr_practice_back/site-packages/pydy/system.py in _Kane_constant_symbols(self)
    586                                                                    
    587         """                                                        
--> 588         from_eoms, from_sym_lists = self._Kane_inlist_insyms()
    589         unique_symbols = set()
    590         for expr in from_eoms:
                          
~/.pyenv/versions/pypy3.5-6.0.0/envs/xr_practice_back/site-packages/pydy/system.py in _Kane_inlist_insyms(self)
    554         # udot, uaux, and uauxdot.                                         
    555         insyms = set(self.eom_method.q[:] + self.eom_method._qdot[:] +
--> 556                      self.eom_method.u[:] + self.eom_method._udot[:] + uaux +                                                                                         
    557                      uauxdot)
    558                                                                        
                                                                       
TypeError: unsupported operand type(s) for +: 'list' and 'tuple'                
```
The culprit is based on self.eom_method._qdot:

```python
In [5]: type(kane._qdot[:])
Out[5]: tuple

In [6]: type(kane._q[:])
Out[6]: list

```

**Comment by moorepants** [comment]
This is a regression that should probably be fixed in SymPy. I've opened:

https://github.com/sympy/sympy/issues/14958

**Comment by extraymond** [comment]
Hi! Since it's still not fixed on the sympy side. I think it would be nice to lock dependency to sympy lower than 1.2 so new users won't be scared by it and miss out a great project.

**Comment by extraymond** [comment]
What I've done as a workaround is to convert those two attributes into list by wrapping it into a list().

**Comment by moorepants** [comment]
You are welcome to submit a fix that makes PyDy work with the multiple versions of sympy. Or better yet, submit a patch to sympy.

**Comment by moorepants** [comment]
Oh I see now. SymPy is unlikely to fix sympy 1.2. So we'd have to make the fixes here if you want it to work with multiple sympy versions.
